### ISSUE TITLE
Unable de download administration app

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#10]
<a href="https://github.com/lduparc"><img src="https://avatars0.githubusercontent.com/u/790935?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lduparc](https://github.com/lduparc)**
_Tuesday May 03, 2016 at 06:46 GMT_
_Originally opened as https://github.com/googlesamples/android-NfcProvisioning/issues/1_

----

Using this sample app with the deviceOwner app installed on the master device, the child device is encrypted and started on Android for Work setup page but it is not able to download the administration app to the child device. 

I'm using a Motorola X Style (XT1572) on Android 6.0 for my tests.
Do I have to define a specific configuration in order to be able to download the admin app ?

Properties are the following : 

```
DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_NAME,
                "com.example.androidmdm");
DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION,
                "https://drive.google.com/file/d/XXXXXXXXXXX/view?usp=sharing");
DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_CHECKSUM,
                "base64 and sha-256 EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION");
```

**Comment by codingjeremy** [comment]
<a href="https://github.com/saddahussain"><img src="https://avatars0.githubusercontent.com/u/20544271?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [saddahussain](https://github.com/saddahussain)**
_Saturday Mar 30, 2019 at 07:53 GMT_

----

You have to provide a downloadable url.

**Comment by sir-friedrich-nietzsche** [comment]
> [<img alt="" width="48" height="48" src="https://avatars0.githubusercontent.com/u/20544271?v=4">](https://github.com/saddahussain) **Comment by [saddahussain](https://github.com/saddahussain)** _Saturday Mar 30, 2019 at 07:53 GMT_
> 
> You have to provide a downloadable url.

Can I use DevicePolicyManager.EXTRA_PROVISIONING_DEVICE_ADMIN_PACKAGE_DOWNLOAD_LOCATION and point to an APK stored on an external media (USB)?
