### ISSUE TITLE
How to install the sample app

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#2]
<a href="https://github.com/lduparc"><img src="https://avatars0.githubusercontent.com/u/790935?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lduparc](https://github.com/lduparc)**
_Tuesday May 03, 2016 at 06:50 GMT_
_Originally opened as https://github.com/googlesamples/android-DeviceOwner/issues/2_

----

I'm using the NfcProvisionning sample app but I'm not able to install the deviceOwner app on the child device. This app is already installed on the master device, the child device is well encrypted and the wifi connected but I receive an error during the admin app download.

I test with a Motorola X Style (XT1572) and a Motorola X Force (XT1580) on Android 6.0

**Comment by pfmaggi** [comment]
Closing as obsolete.

Please reopen if you think this issue is still relevant.
