### ISSUE TITLE
BasicManagedProfile sample not working on Android 10

### ISSUE THREAD

**Issue by mcfoi** [android/enterprise-samples#28]
While the sample woks flawlessly on Android 8.1, on Android 10 the creation of a Work Profile stars anc completes but no DEVICE_ADMIN_ENABLED event is never captured by the BasicDeviceAdminReceiver.
As a consequence the Work Profile is never enabled.

EDIT: adding more detail.
I tryed bypassing the receiver (BasicDeviceAdminReceiver) whose only purpose is starting the Profile enabling process in EnableProfileActivity.
In this class just two things are done:
- setting Profile name
- enabling Profile
It seems that DevicePolicyManager is crashing on setProfileName() or, if commented, on setProfileEnabled: hence Profile is never enabled.
This is confirmed in device Settings where the Profile is available but marked as "not jet available".
The error is:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.basicmanagedprofile/com.example.android.basicmanagedprofile.EnableProfileActivity}: java.lang.SecurityException: No active admin ComponentInfo`

**Comment by lintz18** [comment]
Have you found the solution? I have teh same issue

**Comment by mcfoi** [comment]
> Have you found the solution? I have the same issue

No. I gave up any attempt as is something clearly related with some constraints in recent Android platforms.. ..so nothing we can do about until is somewhat documented. Sorry!

**Comment by lintz18** [comment]
Hey, I've found a solution. 
In case it helps you : [Repo TestDPC ](https://github.com/googlesamples/android-testdpc)

Working on Android 10.
