### ISSUE TITLE
Does this work at all, seriously?

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#3]
<a href="https://github.com/nickfurnesschubb"><img src="https://avatars0.githubusercontent.com/u/12428332?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nickfurnesschubb](https://github.com/nickfurnesschubb)**
_Thursday Aug 18, 2016 at 16:38 GMT_
_Originally opened as https://github.com/googlesamples/android-DeviceOwner/issues/3_

----

I have tried this a few times without success thinking Android 5 was just to qwerky however i have tried with an Android 6 phone and i still cannot get this to work.

I have attached my version of all files. Included with screenshots of my provision app and the error i see when it attempts to go to a web location to get the apk. I have tested this address in a browser to make sure the download works.
I use a checksum utility to generate the checksum value for me.

Can anybody help and point out what is missing. Can anyone hold their hand up and honestly say they have got this working?

[GitHubFiles.zip](https://github.com/googlesamples/android-DeviceOwner/files/425422/GitHubFiles.zip)

[android-DeviceOwner-master.zip](https://github.com/googlesamples/android-DeviceOwner/files/425437/android-DeviceOwner-master.zip)

**Comment by nwagu** [comment]
@codingjeremy did you ever get it to work? This issue title just echoes my mind now

**Comment by pfmaggi** [comment]
I added a section on how to test Device Owner application on a device using `adb`, please reopen this if you still have problems.
