### ISSUE TITLE
provision without nfc

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#4]
<a href="https://github.com/vikas0"><img src="https://avatars1.githubusercontent.com/u/20305290?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vikas0](https://github.com/vikas0)**
_Tuesday Oct 10, 2017 at 11:44 GMT_
_Originally opened as https://github.com/googlesamples/android-DeviceOwner/issues/4_

----

the device i want to install device owner does not have nfc. i have tested with adb shell set device owner for test purpose, but how do i do it to set up unprovisioned device?

**Comment by codingjeremy** [comment]
<a href="https://github.com/adatoo"><img src="https://avatars0.githubusercontent.com/u/1885244?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adatoo](https://github.com/adatoo)**
_Monday Oct 16, 2017 at 20:45 GMT_

----

Not sure if this answers your query. The command to enable device owner is:
```
adb shell dpm set-device-owner com.example.android.deviceowner/.DeviceOwnerReceiver
```
You need to ideally do this on a device that has just been factory reset.

**Comment by pfmaggi** [comment]
I added a section on how to test Device Owner application on a device using `adb`, please reopen this if you still have problems.
