### ISSUE TITLE
There are several errors in the CodeLab docs.

### ISSUE THREAD

**Issue by ntsk** [android/enterprise-samples#43]
### 1. The "adb install" command is incorrect for languages other than English.

https://developer.android.com/codelabs/work-profile-apps#1

There is no `adb pm install` command.

Japanese
![スクリーンショット 0004-09-10 21 02 13](https://user-images.githubusercontent.com/5681281/189482659-562a9e8d-0c8d-4d32-af02-a97800223e45.png)
English
![スクリーンショット 0004-09-10 21 02 30](https://user-images.githubusercontent.com/5681281/189482661-2d0f5cfd-1328-41d1-b8b1-0f3b7d3291e5.png)

The screenshots are in Japanese, but are incorrect in other languages as well.

### 2. "cd" command is out of the code block.
 
https://developer.android.com/codelabs/work-profile-apps#3

![スクリーンショット 0004-09-10 21 03 08](https://user-images.githubusercontent.com/5681281/189482858-2a1899c7-f785-414c-889e-facbb4156508.png)

**Comment by pfmaggi** [comment]
Thanks for reporting these. I'll work on a fix.

**Comment by pfmaggi** [comment]
The english version is now updated. 
I hope to have a new set of translations started in a short time.

**Comment by pfmaggi** [comment]
The translations of the lasted version (Sept. 15th) are starting to be published, starting from the tradition Chinese one. Other languages will follow during the next couple of weeks.

I'm going to close the issue at this moment. Please open a new issue if you find other issues in the codelab.
