### ISSUE TITLE
how do i make my android app device owner programmatically

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#5]
<a href="https://github.com/abhisheklokare"><img src="https://avatars2.githubusercontent.com/u/33583360?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [abhisheklokare](https://github.com/abhisheklokare)**
_Saturday Aug 11, 2018 at 07:00 GMT_
_Originally opened as https://github.com/googlesamples/android-DeviceOwner/issues/5_

----

how do i make my android app device owner programmatically.

**Comment by pfmaggi** [comment]
Making an application Device Owner requires that no users are present on the device. This requires a factory reset of the device if a user was already present.

Tale a look at the usb command: `adb shell dpm set-device-owner` and you can do tests with the [TestDPC application](https://github.com/googlesamples/android-testdpc)
