### ISSUE TITLE
App not showing in manage config dropdown work profile policy manager

### ISSUE THREAD

**Issue by jogigouda** [android/enterprise-samples#58]
I have installed app  ManagedConfigurations and setup the environment with Test DPC application. In working profile while doing manage configuration not showing the app in dropdown. 

PFA
https://user-images.githubusercontent.com/6600162/203516400-c5c0c1de-4a31-4540-b6fb-55fe4d6b43f1.mp4

**Comment by pfmaggi** [comment]
From the video the ManagedConfiguration app is not installed on the work profile (when you switch to the work profile the app is not shown). you should install it on both profile (personal and work).
You can see how this can be done also from Android Studio in this codelab: https://developer.android.com/codelabs/work-profile-apps?hl=en#1

I'm going to close the issue, let me know if you still have this problem after having installed the application on the work profile.
