### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#8]
<a href="https://github.com/ElieGallet"><img src="https://avatars2.githubusercontent.com/u/6837776?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ElieGallet](https://github.com/ElieGallet)**
_Wednesday Mar 01, 2017 at 10:41 GMT_
_Originally opened as https://github.com/googlesamples/android-BasicManagedProfile/issues/8_

----

This app is crashing while (after?) setting a work profile

**Comment by codingjeremy** [comment]
<a href="https://github.com/MichaelMaresca1986"><img src="https://avatars2.githubusercontent.com/u/40027137?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MichaelMaresca1986](https://github.com/MichaelMaresca1986)**
_Saturday Jul 14, 2018 at 19:05 GMT_

----

Dunno

**Comment by codingjeremy** [comment]
<a href="https://github.com/MichaelMaresca1986"><img src="https://avatars2.githubusercontent.com/u/40027137?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MichaelMaresca1986](https://github.com/MichaelMaresca1986)**
_Saturday Jul 14, 2018 at 19:05 GMT_

----

It said this app is crashing

**Comment by yaraki** [comment]
Fixed with #29
