### ISSUE TITLE
BasicManagedProfile App is not working in Android Q device.

### ISSUE THREAD

**Issue by codingjeremy** [android/enterprise-samples#9]
<a href="https://github.com/byodhcl"><img src="https://avatars3.githubusercontent.com/u/54616327?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [byodhcl](https://github.com/byodhcl)**
_Wednesday Aug 28, 2019 at 08:43 GMT_
_Originally opened as https://github.com/googlesamples/android-BasicManagedProfile/issues/9_

----

**Problem:** When tried to install the Sample app(BasicManagedProfile), it is not setting up the work profile into the device hence the app is not setup as DO/PO app.

**Reproduction Steps:**
1)	Install the app into Android Q device(We built the app based on the sample app code with Android 29 version sdk – We also modified the manifest file by changing the sdk version accordingly)
2)	Click on the button “setup profile”.
3)	Observe that – it will be setting up the work profile.
4)	Click on “next” once work profile installation is done.
5)	Observe that - flow will not be redirected into app after clicked on next.
_Expected result:_ Flow should be auto-redirected into App where app should display the option mentioned from the second screenshot attached for this app.
https://github.com/googlesamples/android-BasicManagedProfile/blob/master/screenshots/set_up.png

6)	Observe that - no work profile configuraiton is applied on the device.
_Expected result :_ After installed the work profile, we can see both Personal and Work option enabled from the device.   
7)	Observer that – when manually open the app after installation, still it ask to click on “setup profile” that means our app is not set as “PO” app.
_Expected result:_ It should display the option as mentioned from the 5th step expected result as device is already set as DO owner app.

Attached the video recording by reproducing the issue.
https://drive.google.com/file/d/1mLnDFwSnhB2KLn495DDfitKuvyYiCOqb/view?usp=sharing

Kindly check the issue. Also attached the bug report captured by reproducing the issue.
[bugreport-blueline-QPP6.190730.005-2019-08-28-13-59-30.zip](https://github.com/googlesamples/android-BasicManagedProfile/files/3549951/bugreport-blueline-QPP6.190730.005-2019-08-28-13-59-30.zip)

**Comment by wangduheng** [comment]
I meet too , why? i can found the reason

**Comment by lintz18** [comment]
Has any one found the solution?
